### ISSUE TITLE
Naming of schema.org signals

### ISSUE THREAD

**Issue by erikbosch** [COVESA/vehicle_signal_specification#293]
VSS has some signals from https://schema.org/Car. The naming (e.g. capitalization of letters) is not consistent with other VSS signals, and not always consistent with the capitalization used in schema.org. The expanded names also gets very long, like `Vehicle.VehicleIdentification.ACRISSCode` and `Vehicle.VehicleIdentification.vehicleinteriorColor` . Do we want to do any change? Are the signals actively used by someone today?

```
VSS:
VehicleIdentification.ACRISSCode
VehicleIdentification.vehicleinteriorColor

schema.org:
acrissCode
vehicleInteriorColor
```

**Comment by SebastianSchildt** [comment]
Can we agree, how to handle this?  So that this becomes just "homework" :)

I would suggest
 - remove "Vehicle" from the "VehicleIdentification" subbranch  (but this will be a rbeaking change do we need to deprecate)
 - remove "vehicle" from the datapoints as in "vehicleInteriorColor" 
 - Captitalize first letter of an Attribute , follow Schema.org for the rest ( `Vehicle.Identification.AcrissCode` and `Vehicle.Identifiction.InteriorColor`  (fromt eh examples, I would doubt this belongs under "Identification" at all, but rather under `Vehicle` or `Vehicle.Cabin`)
